### ISSUE TITLE
Fix handling of kwargs in constructor

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audobject#50]
Currently, all attributes of an object are serialized if the constructor accepts `**kwargs`, e.g.:

```python
class Object(audobject.Object):

    def __init__(
            self,
            **kwargs,
    ):
        self.foo = kwargs['foo']
        self.bar = 'not a kwarg'


o = Object(foo='a kwarg')
o.to_yaml_s()
```
```
$__main__.Object==1.0.0:
  foo: a kwarg
  bar: not a kwarg
```

But the expected behavior is:

```
$__main__.Object==1.0.0:
  foo: a kwarg
```

**Comment by hagenw** [comment]
Do I understand it correctly: we only store all attributes when `**kwargs` is given at the moment, otherwise we only store attributes provided as (keyword) arguments, correct?
Or do we always store all attributes?

**Comment by frankenjoe** [comment]
Currently, when the constructor expects `**kwargs` we store **all** attributes. We need to change this to only store the attributes that match with a keyword argument.
