### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by Bahaabrougui** [audeering/audobject#60]
Line : `decorator.py:57`, throws a warning
```python
UserWarning: TupleResolver is deprecated and will be removed with version 1.0.0. Use resolver.Tuple instead.
resolver_obj = resolve()
```

**Comment by frankenjoe** [comment]
The warning should disappear if you replace `TupleResolver` with `resolver.Tuple`.

**Comment by Bahaabrougui** [comment]
Closing as this is not coming from audobject but by the the library calling it.
